### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by cooolgamer** [RedInquisitive/Super-Haxagon#17]
![image](https://user-images.githubusercontent.com/64099608/96620569-e6a1e300-1307-11eb-8a02-1af8b08ff4d5.png)
I installed all ressources and I have that when I try to compile on 3ds...
can you help me?
thanks.

**Comment by RedTopper** [comment]
Ok I've been googling this for the past while and I'm not turning up anything. What toolchain are you using?

**Comment by cooolgamer** [comment]
I don't know what its a toolchain 😅

**Comment by RedTopper** [comment]
A toolchain is a collection of software you use to compile things. There are a few toolchains you can install to build this project:

Microsoft Visual C++ (MSVC):
This is the toolchain that comes with Visual Studio. By installing Visual Studio, you can compile the windows version of this project. Seeing as you want to compile for 3DS, this is probably not what you want.

GNU/G++ on Linux:
These are the set of linux tools available to build for the 3DS/Switch/Linux platform. Looking at your prompt, you're running windows, so this is probably not what you want.

MinGW on MSYS2 ([get it here](https://www.msys2.org/)):
This is the tools to build 3DS, Switch, and Windows builds. [You'll have to follow the guide here to set it up](https://devkitpro.org/wiki/devkitPro_pacman). I can't support any issues you may have following that guide, but many people use it so there should be lots of support online for any issues you may run in to.

There are other toolchains like Cygwin or CodeBlocks, but I don't support those.

**In order to verify that you are having an issue with my project specifically**, I reccomend trying to build some example projects [from this repository first](https://github.com/devkitPro/3ds-examples) to verify that you have everything set up correctly.

Let me know if that helps!

**Comment by cooolgamer** [comment]
I use cmd on windows 😅

**Comment by RedTopper** [comment]
Yeah, you'll have to compile the sample projects and see if those work. I don't have enough information to go off of in the screenshot you gave me.

**Comment by cooolgamer** [comment]
![image](https://user-images.githubusercontent.com/64099608/96987561-7a033000-1523-11eb-8c7e-5f18d11503b9.png)
error when compiling 3ds exemple

**Comment by RedTopper** [comment]
You need to [read the README.md for that project first](https://github.com/devkitPro/3ds-examples/tree/master/audio/opus-decoding) to fix that error.

Unfortunately it does look like I forgot to provide a list of packages required for the 3DS . You'll have to play around with pacman and install all of the dependencies with a bit of trial and error. I'll get around to updating the Makefile to include a comment with a list of packages in some time.

**Comment by cooolgamer** [comment]
ok, thanks, I will do that later 👍

**Comment by cooolgamer** [comment]
![image](https://user-images.githubusercontent.com/64099608/97074743-661e0380-15e1-11eb-9d66-882d01d10dd3.png)
another error

**Comment by RedTopper** [comment]
![image](https://user-images.githubusercontent.com/6108605/97094975-8e2c5780-161f-11eb-98f0-94b32ce9c8be.png)

That example works fine for me out of the box. Something is wrong with your toolchain.

**Comment by RedTopper** [comment]
I'll be closing this issue for now, but if you have problems feel free to open this issue back up again.
